# Generated by Django 5.2.8 on 2025-12-02 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='authorNickname',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='emojiSequence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='translation',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
