# Generated by Django 5.2.8 on 2025-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0002_story_authornickname_story_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='emojiSequence',
            new_name='emoji_sequence',
        ),
        migrations.RemoveField(
            model_name='story',
            name='authorNickname',
        ),
        migrations.AddField(
            model_name='story',
            name='author_nickname',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
